NFLTeams/Controllers/FavoritesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NFLTeams.Models;

namespace NFLTeams.Controllers
{
    public class FavoritesController : Controller
    {
        private TeamContext context;
        public FavoritesController(TeamContext ctx) => context = ctx;

        [HttpGet]
        public ViewResult Index()
        {
            // get favorite teams and current conference and division
            // from session, pass to view in view model
            var session = new NFLSession(HttpContext.Session);
            var model = new TeamsViewModel
            {
                ActiveConf = session.GetActiveConf(),
                ActiveDiv = session.GetActiveDiv(),
                Teams = session.GetMyTeams(),
                Username = session.GetName()
            };

            return View(model);
        }

        [HttpPost]
        public RedirectToActionResult Add(Team team)
        {
            // get full team data from database
            team = context.Teams
                 .Include(t => t.Conference)
                 .Include(t => t.Division)
                 .Where(t => t.TeamID == team.TeamID)
                 .FirstOrDefault() ?? new Team();

            // add team to favorite teams in session
            var session = new NFLSession(HttpContext.Session);
            var teams = session.GetMyTeams();
            teams.Add(team);
            session.SetMyTeams(teams);

            // set add message
            TempData["message"] = $"{team.Name} added to your favorites";

            // redirect to Home page
            return RedirectToAction("Index", "Home", 
                new
                {
                    ActiveConf = session.GetActiveConf(),
                    ActiveDiv = session.GetActiveDiv()
                });
        }

        [HttpPost]
        public RedirectToActionResult Delete()
        {
            // delete favorite teams from session
            var session = new NFLSession(HttpContext.Session);
            session.RemoveMyTeams();

            // set delete message
            TempData["message"] = "Favorite teams cleared";

            // redirect to Home page
            return RedirectToAction("Index", "Home",
                new {
                    ActiveConf = session.GetActiveConf(),
                    ActiveDiv = session.GetActiveDiv()
                });
        }
    }
}

NFLTeams/Controllers/NameController.cs
using Microsoft.AspNetCore.Mvc;
using NFLTeams.Models;

namespace NFLTeams.Controllers
{
    public class NameController : Controller
    {
        [HttpGet]
        public ViewResult Index()
        {
            var session = new NFLSession(HttpContext.Session);
            var model = new TeamsViewModel
            {
                ActiveConf = session.GetActiveConf(),
                ActiveDiv = session.GetActiveDiv(),
                Teams = session.GetMyTeams(),
                Username = session.GetName()
            };
            return View(model);
        }
        [HttpPost]
        public RedirectToActionResult Change(TeamsViewModel model)
        {
            var session = new NFLSession(HttpContext.Session);
            session.SetName(model.Username);

            return RedirectToAction("Index", "Home",
                new
                {
                    ActiveConf = session.GetActiveConf(),
                    ActiveDiv = session.GetActiveDiv()
                });
        }
    }
}

NFLTeams/Views/Favorites/Index.cshtml
@model TeamsViewModel
@{
    ViewData["Title"] = "Favorites";
}

<div class="text-center">

    <h2>@(String.IsNullOrEmpty(Model.Username) ? "My" : Model.Username + 
        "'s") Favorites</h2>

    <form asp-action="Delete" method="post">
        <a asp-action="Index" asp-controller="Home" class="btn btn-primary"
           asp-route-activeConf ="@Model.ActiveConf" 
           asp-route-activeDiv="@Model.ActiveDiv">
            Back to Home Page
        </a>
        <a asp-action="Index" asp-controller="Name" class="btn btn-primary">
            Change Name
        </a>
        <button type="submit" class="btn btn-primary">
            Clear Favorites
        </button>
    </form>
    <br />
</div>


<div class="row">
    <div class="col-8 offset-2">
        <ul class="list-group">
            @foreach (Team team in Model.Teams)
            {
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-sm-4">
                            <img src="~/images/@team.LogoImage" alt="" />
                        </div>
                        <div class="col-sm-4">
                            @team.Name
                        </div>
                        <div class="col-sm-4">
                            @team.Conference.Name @team.Division.Name
                        </div>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>