NFLTeams/Controllers/FavoritesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NFLTeams.Models;

namespace NFLTeams.Controllers
{
    public class FavoritesController : Controller
    {
        private TeamContext context;
        public FavoritesController(TeamContext ctx) => context = ctx;

        [HttpGet]
        public ViewResult Index()
        {
            // get favorite teams and current conference and division
            // from session, pass to view in view model
            var session = new NFLSession(HttpContext.Session);
            var model = new TeamsViewModel
            {
                ActiveConf = session.GetActiveConf(),
                ActiveDiv = session.GetActiveDiv(),
                Teams = session.GetMyTeams(),
                Username = session.GetName()
            };

            return View(model);
        }

        [HttpPost]
        public RedirectToActionResult Add(Team team)
        {
            // get full team data from database
            team = context.Teams
                 .Include(t => t.Conference)
                 .Include(t => t.Division)
                 .Where(t => t.TeamID == team.TeamID)
                 .FirstOrDefault() ?? new Team();

            // add team to favorite teams in session
            var session = new NFLSession(HttpContext.Session);
            var teams = session.GetMyTeams();
            teams.Add(team);
            session.SetMyTeams(teams);

            // set add message
            TempData["message"] = $"{team.Name} added to your favorites";

            // redirect to Home page
            return RedirectToAction("Index", "Home", 
                new
                {
                    ActiveConf = session.GetActiveConf(),
                    ActiveDiv = session.GetActiveDiv()
                });
        }

        [HttpPost]
        public RedirectToActionResult Delete()
        {
            // delete favorite teams from session
            var session = new NFLSession(HttpContext.Session);
            session.RemoveMyTeams();

            // set delete message
            TempData["message"] = "Favorite teams cleared";

            // redirect to Home page
            return RedirectToAction("Index", "Home",
                new {
                    ActiveConf = session.GetActiveConf(),
                    ActiveDiv = session.GetActiveDiv()
                });
        }
    }
}

NFLTeams/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NFLTeams.Models;

namespace NFLTeams.Controllers
{
    public class HomeController : Controller
    {
        private TeamContext context;
        public HomeController(TeamContext ctx) => context = ctx;

        public ViewResult Index(TeamsViewModel model)
        {
            // store active conference and division in session
            var session = new NFLSession(HttpContext.Session);
            session.SetActiveConf(model.ActiveConf);
            session.SetActiveDiv(model.ActiveDiv);

            // get conferences and divisions from database
            model.Conferences = context.Conferences.ToList();
            model.Divisions = context.Divisions.ToList();

            // get teams from database - filter by conference and division
            IQueryable<Team> query = context.Teams.OrderBy(t => t.Name);
            if (model.ActiveConf != "all")
                query = query.Where(
                    t => t.Conference.ConferenceID.ToLower() == model.ActiveConf.ToLower());
            if (model.ActiveDiv != "all")
                query = query.Where(
                    t => t.Division.DivisionID.ToLower() == model.ActiveDiv.ToLower());
            model.Teams = query.ToList();

            // pass view model to view
            return View(model);
        }

        public ViewResult Details(string id)
        {
            // get current conference and division from session
            // and pass them to the view in the view model
            var session = new NFLSession(HttpContext.Session);
            var model = new TeamsViewModel
            {
                Team = context.Teams
                    .Include(t => t.Conference)
                    .Include(t => t.Division)
                    .FirstOrDefault(t => t.TeamID == id) ?? new Team(),
                ActiveDiv = session.GetActiveDiv(),
                ActiveConf = session.GetActiveConf()
            };
            return View(model);
        }

    }
}

NFLTeams/Views/Home/Details.cshtml
@model TeamsViewModel
@{
    ViewData["Title"] = "Team Details";
}

<h2 class="text-center p-2">Team Details</h2>

<div class="row">
    <div class="col">
        <ul class="list-group text-center">
            <li class="list-group-item">
                <img src="~/images/@Model.Team.LogoImage" alt="" />
                <h3>@Model.Team.Name</h3>
            </li>
            <li class="list-group-item">
                <h4>Conference: @Model.Team.Conference.Name</h4>
            </li>
            <li class="list-group-item">
                <h4>Division: @Model.Team.Division.Name</h4>
            </li>
            <li class="list-group-item">
                <form asp-action="Add" asp-controller="Favorites" method="post">
                    <a asp-action="Index" class="btn btn-primary"
                       asp-route-activeConf="@Model.ActiveConf"
                       asp-route-activeDiv="@Model.ActiveDiv">Return to Home Page</a>
                    <button type="submit" class="btn btn-primary">
                        Add to Favorites
                    </button>
                    <input type="hidden" asp-for="Team.TeamID" />
                </form>
            </li>
        </ul>
    </div>
</div>

NFLTeams/Views/Home/Index.cshtml
@model TeamsViewModel
@{
    ViewData["Title"] = "NFL Teams";
}
<div class="row">
    <div class="col-sm-3">
        <h3 class="mt-3">Conference</h3>
        <div class="list-group">
            <a asp-action="Index"
                asp-route-activeConf="all"
                asp-route-activeDiv="@Model.ActiveDiv"
                class="list-group-item @Model.CheckActiveConf("all")">
                All
            </a>
            @foreach (Conference conf in Model.Conferences)
            {
                <a asp-action="Index"
                   asp-route-activeConf="@conf.ConferenceID"
                   asp-route-activeDiv="@Model.ActiveDiv"
                   class="list-group-item @Model.CheckActiveConf(conf.ConferenceID)">
                    @conf.Name
                </a>
            }
        </div>
        <h3 class="mt-3">Division</h3>   
        <div class="list-group">
            <a asp-action="Index"
                asp-route-activeConf="@Model.ActiveConf"
                asp-route-activeDiv="all"
                class="list-group-item @Model.CheckActiveDiv("all")">
                All
            </a>
            @foreach (Division div in Model.Divisions)
            {
                <a asp-action="Index"
                   asp-route-activeConf="@Model.ActiveConf"
                   asp-route-activeDiv="@div.DivisionID"
                   class="list-group-item @Model.CheckActiveDiv(div.DivisionID)">
                    @div.Name
                </a>
            }
        </div>
    </div>
    <div class="col-sm-9">
        <ul class="list-inline">
            @foreach (Team team in Model.Teams)
            {
                <li class="list-inline-item">
                    <a asp-action="Details" asp-route-id="@team.TeamID">
                        <img src="~/images/@team.LogoImage" alt="@team.Name"
                             title="@team.Name | @team.Conference.Name @team.Division.Name" />
                    </a>
                </li>
            }
        </ul>
    </div>
</div>